# Generated by Django 4.2.5 on 2023-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Account_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='Balance',
            field=models.IntegerField(),
        ),
    ]
