# Generated by Django 4.2.5 on 2023-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0002_alter_bank_account_no_alter_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Account_no',
            field=models.CharField(max_length=250),
        ),
    ]
