# Generated by Django 4.2.5 on 2023-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0003_alter_bank_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
